language: objective-c

os: osx
osx_image: xcode10.1

xcode_project: Structure.xcodeproj

xcode_scheme:
    - Structure iOS
    - Structure macOS
    - Structure tvOS

xcode_sdk:
    - iphonesimulator12.1
    - macosx10.14
    - appletvsimulator12.1

matrix:
    exclude:
        - xcode_scheme: Structure iOS
          xcode_sdk: macosx10.14
        - xcode_scheme: Structure iOS
          xcode_sdk: appletvsimulator12.1
        - xcode_scheme: Structure macOS
          xcode_sdk: iphonesimulator12.1
        - xcode_scheme: Structure macOS
          xcode_sdk: appletvsimulator12.1
        - xcode_scheme: Structure tvOS
          xcode_sdk: iphonesimulator12.1
        - xcode_scheme: Structure tvOS
          xcode_sdk: macosx10.14

script:
    - xcodebuild clean build -sdk "${TRAVIS_XCODE_SDK}" -project "${TRAVIS_XCODE_PROJECT}" -scheme "${TRAVIS_XCODE_SCHEME}" CODE_SIGNING_REQUIRED=NO
