language: objective-c

os: osx
osx_image: xcode11

xcode_project: Restructure.xcodeproj

xcode_scheme:
    - Restructure iOS
    - Restructure macOS
    - Restructure tvOS

xcode_sdk:
    - iphonesimulator13.0
    - macosx10.15
    - appletvsimulator13.0

matrix:
    exclude:
        - xcode_scheme: Restructure iOS
          xcode_sdk: macosx10.15
        - xcode_scheme: Restructure iOS
          xcode_sdk: appletvsimulator13.0
        - xcode_scheme: Restructure macOS
          xcode_sdk: iphonesimulator13.0
        - xcode_scheme: Restructure macOS
          xcode_sdk: appletvsimulator13.0
        - xcode_scheme: Restructure tvOS
          xcode_sdk: iphonesimulator13.0
        - xcode_scheme: Restructure tvOS
          xcode_sdk: macosx10.15

script:
    - swift test
