language: objective-c

os: osx
osx_image: xcode11.6

xcode_project: Restructure.xcodeproj

xcode_scheme:
    - Restructure iOS
    - Restructure macOS
    - Restructure tvOS

xcode_sdk:
    - iphonesimulator13.6
    - macosx10.15
    - appletvsimulator13.4

matrix:
    exclude:
        - xcode_scheme: Restructure iOS
          xcode_sdk: macosx10.15
        - xcode_scheme: Restructure iOS
          xcode_sdk: appletvsimulator13.4
        - xcode_scheme: Restructure macOS
          xcode_sdk: iphonesimulator13.6
        - xcode_scheme: Restructure macOS
          xcode_sdk: appletvsimulator13.4
        - xcode_scheme: Restructure tvOS
          xcode_sdk: iphonesimulator13.6
        - xcode_scheme: Restructure tvOS
          xcode_sdk: macosx10.15

script:
    - swift test
